#!/usr/bin/env python

if __name__ != "__main__":
	print("This tool shouldn't be imported silly!")
else:
	import argparse
	import sys

	desc = "\n".join([
		"Removes trailing whitespace and appends a newline to every line.",
		"WARNING: Caution is advised when using the --file option as changes to the file are permanent!"
	])

	parser = argparse.ArgumentParser(description=desc)
	parser.add_argument(
		"-f", "--file",
		help="Trim trailing whitespace from each line in the file.",
		nargs="*")
	parser.add_argument(
		"-l", "--leading",
		help="Trim leading whitespace instead of trailing.",
		action="store_true")
	parser.add_argument(
		"-b", "--both",
		help="Trim leading and trailing whitespace.",
		action="store_true")
	parser.add_argument(
		"-t", "--terse",
		help="Suppress all errors to STDOUT.",
		action="store_true")
	args = parser.parse_args()

	def trim(lines):
		if args.both:
			lines = "\n".join(list(map(str.strip, lines)))
		elif args.leading:
			lines = list(map(str.lstrip, lines))
		else:
			lines = "\n".join(list(map(str.rstrip, lines)))
		return lines

	try:
		if args.file:
			for file_path in args.file:
				with open(file_path, "r") as stream:
					lines = stream.readlines()
				with open(file_path, "w") as stream:
					stream.writelines(trim(lines))
		else:
			sys.stdout.writelines(trim(sys.stdin.readlines()))
	except BaseException as error:
		if not args.terse:
			print(error)
